version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: teencare-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teencare
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: teencare-backend
    restart: always
    depends_on:
      - db
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/teencare?schema=public
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: teencare-frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000/api
    ports:
      - "3000:3000"

volumes:
  postgres_data: